Update FastClasspathScanner.java
Somehow Java 8 compiler with target 1.7 gives error
E:\products\fast-classpath-scanner-master\src\com\lukehutch\fastclasspathscanner\FastClasspathScanner.java:638: error: i
ncompatible types: ArrayList<Object> cannot be converted to ArrayList<String>
        ArrayList<String> interfaces = interfaceCount > 0 ? new ArrayList<>() : null;